"""initial migration

Revision ID: 3eaaf988825f
Revises: 
Create Date: 2025-05-07 04:17:39.503435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eaaf988825f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jp', sa.String(), nullable=True),
    sa.Column('en', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('municipality_code', sa.String(), nullable=True),
    sa.Column('municipality_name', sa.String(), nullable=True),
    sa.Column('furigana', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('area_address_with_zipcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('area_en', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipalities',
    sa.Column('municipality_code', sa.String(length=6), nullable=False),
    sa.Column('municipality_name', sa.String(), nullable=False),
    sa.Column('furigana', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('municipality_code')
    )
    op.create_table('sapporo_city_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sorting_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categories', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_sorting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('sorting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sorting_id'], ['sorting_numbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sorting_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sorting_id', sa.Integer(), nullable=False),
    sa.Column('jp', sa.String(), nullable=True),
    sa.Column('en', sa.String(), nullable=True),
    sa.Column('zh', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sorting_id'], ['sorting_numbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waste_item_with_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['sorting_numbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waste_item_with_id')
    op.drop_table('sorting_translations')
    op.drop_table('area_sorting')
    op.drop_table('sorting_numbers')
    op.drop_table('sapporo_city_area')
    op.drop_table('municipalities')
    op.drop_table('area_address_with_zipcode')
    op.drop_table('admin_info')
    op.drop_table('address_translation')
    # ### end Alembic commands ###
