"""add payment_status and payment_date to admin_info

Revision ID: b288dee8bf1b
Revises: 1ceb0eea8f33
Create Date: 2025-04-20 08:43:37.842482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b288dee8bf1b'
down_revision: Union[str, None] = '1ceb0eea8f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_info', sa.Column('payment_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_info', 'payment_date')
    # ### end Alembic commands ###
